name: npm test
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/npm-test.yml"
  pull_request:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/npm-test.yml"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  npm-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, node-version: "20" }
          - { os: windows-latest, node-version: "18" }
          - { os: macos-latest, node-version: "20" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test